### ISSUE TITLE
Some questions about data processing

### ISSUE THREAD

**Issue by githwd2016** [shubhamagarwal92/mmd#8]
In dialogue_data.py, I find this sentence: "if 'search_criteria' in utterance['utterance']:"(line 161).
However, in the data provided by Amrita Saha, utterance['utterance'] doesn't contain the key 'search_criteria' or 'compulsory_fields'. Moreover, I have run the script and find there is nothing in "train_search_criteria.txt".

Thank you in advance.

**Comment by shubhamagarwal92** [comment]
`search_criteria` or `compulsory_fields` is present whenever a query is fired to the server to retrieve the results. Refer Section 3.2 of our [SCAI paper](https://arxiv.org/pdf/1810.11954.pdf). Probably you might have seen the initial top cases of the txt file. 

Also as mentioned in pre-processing section of README:
Alternatively you can also download the data for context of 2 and 5 (as well as pickled Shah et al. data) that we used for training from this [link](https://www.dropbox.com/s/yz31j1zd3vvjwrw/data.zip?dl=0).

**Comment by githwd2016** [comment]
I download data from the [link](https://drive.google.com/drive/folders/1JOGHzideeAsmykMUQD3z7aGFg-M4QlE2?usp=sharing) provided by Shah et al. However, in their dataset, utterance only contain **nlg**, **images**, **false nlg** and **false images**, without **search_criteria** or **compulsory_fields**. [data_description](https://amritasaha1812.github.io/MMD/download/). Do they change the dataset? 
Of course, the data provided by you is complete. I just wonder how you get the **search_criteria** and **compulsory_fields** since original dataset doesn't contain them.

**Comment by shubhamagarwal92** [comment]
I suggest you look into the raw json files that they provide to get a better picture. They didnt change the dataset AFAIK.

Since they were not using the query while modelling, they chose to omit it in the description. (By the way, there were some issues with their data processing as well. See [1](https://github.com/amritasaha1812/MMD_Code/issues/2) and [2](https://github.com/amritasaha1812/MMD_Code/issues/1).) 

Feel free to ask any other question or close this issue.

**Comment by shubhamagarwal92** [comment]
By the way, did you also face this issue related to #5 ?

**Comment by githwd2016** [comment]
I have checked the raw json files and still didn't find the fields **search_criteria** or **compulsory_fields**.

As for #5, I have fixed the second and third bugs.

**Comment by shubhamagarwal92** [comment]
Example: `dataset/v2/train/572_243.json`, line 48

![Screen Shot 2019-06-05 at 11 56 30 PM](https://user-images.githubusercontent.com/7984532/59012986-c72b1880-87ed-11e9-92fe-18882aad9df2.png)

Also, I would appreciate if you could open a PR, related to the bugs. Otherwise, I will try to rectify soon!

**Comment by githwd2016** [comment]
My 572_243.json is different with yours. I have sent it to your by e-mail.
<img width="835" alt="屏幕快照 2019-06-06 下午3 09 00" src="https://user-images.githubusercontent.com/20674430/59013642-08164200-886d-11e9-99a6-414127dfbcc1.png">

**Comment by shubhamagarwal92** [comment]
I see. Probably they did update the dataset then. Better ask Shah et al. for this version of dataset. You could anyway use the data that I provided.

**Comment by githwd2016** [comment]
I have open a PR to fix two bugs.

**Comment by shubhamagarwal92** [comment]
Thanks. Really appreciate this. I will also look and recover the other config files for #6 . Let me know if you have any other issue.

**Comment by githwd2016** [comment]
Have you checked the result with config version 8？

**Comment by shubhamagarwal92** [comment]
I hope this issue is resolved! Closing this now. Re-open if it still persists
